name: "Log every 1 minute"
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Print a log message
        run: echo "This action runs every 1 minute."
